### ISSUE TITLE
Can't find webpack.config.js on Windows

### ISSUE THREAD

**Issue by RinkAttendant6** [BohdanTkachenko/eslint-plugin-require-path-exists#26]
The plugin doesn't seem to build the path correctly on Windows. The exact same code works fine on Linux.

## `.eslintrc.yaml`
```yaml
---
root: true
env:
    browser: true
    node: true
    es6: true
parserOptions:
    ecmaVersion: 8
    sourceType: module
plugins:
    - require-path-exists
extends:
    - eslint:recommended
    - plugin:require-path-exists/recommended
rules:
    require-path-exists/exists:
        - error
        -
            webpackConfigPath: webpack.config.js
```

## `webpack.config.js`
```js
module.exports = {
    resolve: {
        alias: {
            '@includes': require('path').resolve(__dirname, 'public', 'global', 'resources', 'js')
        }
    }
};
```

## Error
`grunt eslint` gives me this output:
> Warning: Error while loading rule 'require-path-exists/exists': Cannot load Webpack config: Cannot find module 'Z:GitHubProject1webpack.config.js' Use --force to continue.
